### PR TITLE
Updated Humann2 dependencies

### PR DESCRIPTION
**Pull request by semarpetrus**
**travis.yml:**
- Humann2 has a library from an old diamond version and form what I've read they have not released a new version.
- Metaphlan needs the "utils" folder.

**test_humann2.py:**
- assertItemEqual was depreciated in python 3.6.

### CODE REVIEW

**Comment by jdereus** [comment]
Can one of the admins verify this patch?

**Comment by josenavas** [comment]
Add to whitelist

**Comment by semarpetrus** [comment]
On my machine Humann2 takes over 10 mins because its running bowtie and diamond which is the error given by the travis check. Is there a way to increase the time limit before a timeout?

**Comment by antgonza** [comment]
Check: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by josenavas** [comment]
It looks like Jenkins is up and running?

**Comment by antgonza** [comment]
Jenkins : Icreates a new env but it's not running/installing/testing anything

**Pull request merged**
