### PR TITLE
Adding kneaddata pipeline

### PR DESCRIPTION
**Pull request by jdereus**
modify travis.yml.  remove -U.  readd trimmomatic conda install.  will use this as new baseline for testing environment on travis system.

### CODE REVIEW

**Comment by jdereus** [comment]
retest this please

**Comment by jdereus** [comment]
retest this please

**Comment by jdereus** [comment]
retest this please

**Comment by jdereus** [comment]
retest this please

**Comment by jdereus** [comment]
retest this please

**Comment by antgonza** [comment]
Thank you for fixing!! Closing in favor of: https://github.com/qiita-spots/qp-shotgun/pull/21 so I can fix comments from reviewers.

**Pull request closed without merging**
